### ISSUE TITLE
Fails to build with Python 3.10, "cannot import name 'MutableMapping' from 'collections'"

### ISSUE THREAD

**Issue by jonathonf** [AGProjects/python3-otr#2]
MutableMapping was removed in Python 3.10, solution might be to use `collections.abc.MutableMapping` instead?

Using the AUR package https://aur.archlinux.org/packages/python-otr/ on Arch Linux:

```
Traceback (most recent call last):
  File "/build/python-otr/src/python3-otr-2.0.1/setup.py", line 5, in <module>
    from otr import __info__ as package_info
  File "/build/python-otr/src/python3-otr-2.0.1/otr/__init__.py", line 3, in <module>
    from application.notification import NotificationCenter, NotificationData, IObserver
  File "/usr/lib/python3.10/site-packages/application/notification.py", line 11, in <module>
    from application import log
  File "/usr/lib/python3.10/site-packages/application/log/__init__.py", line 11, in <module>
    from application.python import Null
  File "/usr/lib/python3.10/site-packages/application/python/__init__.py", line 5, in <module>
    from application.python.types import NullType
  File "/usr/lib/python3.10/site-packages/application/python/types.py", line 5, in <module>
    from application.python.decorator import preserve_signature
  File "/usr/lib/python3.10/site-packages/application/python/decorator.py", line 7, in <module>
    from application.python.weakref import weakobjectmap
  File "/usr/lib/python3.10/site-packages/application/python/weakref.py", line 4, in <module>
    from collections import MutableMapping, deque
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by jonathonf** [comment]
Sorry, filed this in the wrong place. The bug here is with `python3-application`. PR to fix, https://github.com/AGProjects/python3-application/pull/3
